######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 13 18:20:05 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += script

# Input
HEADERS += canvas.h window.h canvasfull.h
SOURCES += canvas.cpp main.cpp window.cpp canvasfull.cpp

# # Default build is debug
# CONFIG += debug
# CONFIG -= release

# CONFIG += console
